import Head from 'next/head'
import AuthInfoOnFrontend from "../components/AuthInfoOnFrontend";
import AuthenticationButtons from "../components/AuthenticationButtons";
import AuthenticatedRequestToBackend from "../components/AuthenticatedRequestToBackend";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <AuthenticationButtons/>
                <AuthInfoOnFrontend/>
                <AuthenticatedRequestToBackend/>
            </main>
        </div>
    )
}
